apiVersion: v1
kind: Pod
metadata:
  name: odoo-postgres-pod
spec:
  containers:
    - name: odoo
      image: odoo:latest
      env:
        - name: POSTGRES_DB
          value: mydb
        - name: POSTGRES_USER
          value: myuser
        - name: POSTGRES_PASSWORD
          value: mypassword
        - name: POSTGRES_HOST
          value: postgres
      ports:
        - name: odoo-port
          containerPort: 8069
    - name: postgres
      image: postgres:latest
      env:
        - name: POSTGRES_DB
          value: mydb
        - name: POSTGRES_USER
          value: myuser
        - name: POSTGRES_PASSWORD
          value: mypassword
      ports:
        - name: postgres-port
          containerPort: 5432
